
[project]
name = "red_utils"
version = "0.1.0"
description = "Collection of utility scripts/functions that I use frequently."
authors = [
    {name = "redjax", email = "none@none.com"},
]
dependencies = [
    "msgpack>=1.0.5",
    "loguru>=0.7.0",
    "httpx>=0.24.1",
    "diskcache>=5.6.1",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
"Homepage" = "https://github.com/redjax/red-utils"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.0.278",
    "pytest>=7.4.0",
    "black>=23.7.0",
]

[tool.pdm.scripts]

## Format scripts
# Check only, don't fix
check = {cmd = "black ."}
#  Check and fix
format = {cmd = "ruff check . --fix"}

## Start scripts
#  Run main app or script. Launches from app/
# start = { shell = "cd app && pdm run python main.py"}

## Export requirement scripts
#  Export production requirements
export = {cmd = "pdm export --prod -o requirements.txt --without-hashes"}
#  Export only development requirements
export-dev = {cmd = "pdm export -d -o requirements.dev.txt --without-hashes"}
## Uncomment if/when using a CI group
# export-ci = {cmd = "pdm export -G ci -o requirements.ci.txt --without-hashes"}
