[project]
name = "red_utils"
version = "0.1.6"
description = "Collection of utility scripts/functions that I use frequently."
authors = [
    { name = "redjax", email = "none@none.com" },
]
dependencies = [
    "msgpack>=1.0.5",
    "loguru>=0.7.0",
    "httpx>=0.24.1",
    "diskcache>=5.6.1",
    "self>=2020.12.3",
    "pdm-bump>=0.7.1",
]
requires-python = ">=3.11"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/redjax/red-utils"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.0.278",
    "pytest>=7.4.0",
    "black>=23.7.0",
    "semantic-release>=0.1.0",
]

[tool.pdm.scripts.check]
cmd = "black ."

[tool.pdm.scripts.format]
cmd = "ruff check . --fix"

[tool.pdm.scripts.export]
cmd = "pdm export --prod -o requirements.txt --without-hashes"

[tool.pdm.scripts.export-dev]
cmd = "pdm export -d -o requirements.dev.txt --without-hashes"

[tool.semantic_release]
version_variable = "pyproject.toml:version" # version location
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
build_command = "pdm build"              # build dists
dist_path = "dist/"                         # where to put dists
upload_to_release = true                    # auto-create GitHub release
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
patch_without_tag = true                    # patch release by default